//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Interop_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("InteropAbstraction", Namespace="http://tempuri.org/Interop_v1_0.xsd", IsNullable=false)]
    public partial class InteropAbstractionType {
        
        private ServiceType[] servicesField;
        
        private ServiceProfileType[] serviceProfilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Service", IsNullable=false)]
        public ServiceType[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ServiceProfile", IsNullable=false)]
        public ServiceProfileType[] ServiceProfiles {
            get {
                return this.serviceProfilesField;
            }
            set {
                this.serviceProfilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class ServiceType {
        
        private ListenerType[] listenersField;
        
        private object interfacesField;
        
        private MethodType[] methodsField;
        
        private string nameField;
        
        private string serviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Listener", IsNullable=false)]
        public ListenerType[] Listeners {
            get {
                return this.listenersField;
            }
            set {
                this.listenersField = value;
            }
        }
        
        /// <remarks/>
        public object Interfaces {
            get {
                return this.interfacesField;
            }
            set {
                this.interfacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Method", IsNullable=false)]
        public MethodType[] Methods {
            get {
                return this.methodsField;
            }
            set {
                this.methodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class ListenerType {
        
        private object protocolsField;
        
        private ListenerTypeCallType callTypeField;
        
        private string listenerAddressField;
        
        /// <remarks/>
        public object Protocols {
            get {
                return this.protocolsField;
            }
            set {
                this.protocolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ListenerTypeCallType callType {
            get {
                return this.callTypeField;
            }
            set {
                this.callTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listenerAddress {
            get {
                return this.listenerAddressField;
            }
            set {
                this.listenerAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class ServiceProfileType {
        
        private ProfileServiceRefType[] profileServiceRefField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProfileServiceRef")]
        public ProfileServiceRefType[] ProfileServiceRef {
            get {
                return this.profileServiceRefField;
            }
            set {
                this.profileServiceRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class ProfileServiceRefType {
        
        private string serviceRefIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceRefId {
            get {
                return this.serviceRefIdField;
            }
            set {
                this.serviceRefIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class MethodType {
        
        private ParameterType[] parameterField;
        
        private string nameField;
        
        private string returnValueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public ParameterType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnValueType {
            get {
                return this.returnValueTypeField;
            }
            set {
                this.returnValueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public partial class ParameterType {
        
        private string nameField;
        
        private string logicalDataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string logicalDataType {
            get {
                return this.logicalDataTypeField;
            }
            set {
                this.logicalDataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Interop_v1_0.xsd")]
    public enum ListenerTypeCallType {
        
        /// <remarks/>
        WithinSameProcess,
        
        /// <remarks/>
        InterprocessWithinSameMachine,
        
        /// <remarks/>
        Network,
    }
}
